apiVersion: v1
kind: Service
metadata:
  name: auth-webhook
  namespace: kube-system
spec:
  selector:
    app: auth-webhook
  ports:
  - port: 443
    targetPort: 8080
    protocol: TCP
    name: https